### ISSUE TITLE
swaggerhub

### ISSUE THREAD

**Issue by mikeqoo1** [shuming-yu/demo#1]
https://app.swaggerhub.com/apis/MIKEQOO123/shumingyu/1.0.0

**Comment by shuming-yu** [comment]
/ 回傳使用者 -> 異常, 請修改後面路徑, 我再測試 (ex. shuming/alluser 
![image](https://github.com/shuming-yu/demo/assets/85677360/a780f92f-427a-421f-a7de-f428f0c466b3)

**Comment by shuming-yu** [comment]
post -> 新增後結果異常 ( Account: '', Username: '' )
![image](https://github.com/shuming-yu/demo/assets/85677360/81735d5b-f802-410f-bbb2-ac3550fd8371)

**Comment by mikeqoo1** [comment]
靠腰 你有看喔 我都忘了來這邊看 你打LoL 也沒跟我說 死腦包

**Comment by mikeqoo1** [comment]
http://34.80.185.163/swagger/index.html
