### ISSUE TITLE
hi!

### ISSUE THREAD

**Issue by mikeqoo1** [shuming-yu/demo#3]
你的網站連結給我

我想弄個進度條也方便我開nici家族的時候連動

反正你用githubio不用錢 我的主機還要錢呢...QAQ

**Comment by shuming-yu** [comment]
readme 就看的到了齁

https://shuming-yu.github.io/demo/dist/#/
後台 : https://shuming-yu.github.io/demo/dist/#/login

**Comment by mikeqoo1** [comment]
OK 那你的首頁可以好看一點嗎?  https://shuming-yu.github.io/demo/dist/#/ 

真的不像購物網站

**Comment by shuming-yu** [comment]
首頁最後再搞啦  不急
先科簡單的使用者商品頁面
https://shuming-yu.github.io/demo/dist/#/userboard/cart
